### ISSUE TITLE
Correction Files

### ISSUE THREAD

**Issue by ajrbyers** [openlibhums/typesetting#154]
Editors currently must select a file when creating a correction task, this should not be required anymore.

**Comment by ajrbyers** [comment]
> I've seen editors using this feature to share their annotated files with the typesetters. I don't think there is an alternative approach at the moment. The only other option they have is to share files uploaded by proofreaders

Perhaps for a correction we should show all the files available and allow them to select what is shared per #152 ?

**Comment by mauromsl** [comment]
> > I've seen editors using this feature to share their annotated files with the typesetters. I don't think there is an alternative approach at the moment. The only other option they have is to share files uploaded by proofreaders
> 
> Perhaps for a correction we should show all the files available and allow them to select what is shared per #152 ?

yep, that sounds good. Maybe throw in an upload box too so they can upload a file at that point if needed as well
