### ISSUE TITLE
Display text from "Typesetting Task" field on "Review Typesetting" screen

### ISSUE THREAD

**Issue by pgoussy** [openlibhums/typesetting#217]
When I am making an initial typesetting assignment--asking the typesetter to create a **1st-pass** typeset file--I use the Define The Task/Typesetting Task field to simply describe the assignment (e.g., "Create 1pass PDF from final copyedited manuscript"). When I am creating a new typesetting assignment to request revisions, there is typically author feedback in the form of Notes or an attached file, so I use the Typesetting Task field to point the typesetter to those notes (e.g., "Create 2pass PDF by incorporating author feedback - see Notes and/or attachments") .

However, in cases where I review typeset files myself (rather than assigning to the author) I do not have a formal Proofreading Assignment to add notes/files to. If there are only 1-2 corrections required, I will typically describe those corrections in the Typesetting Task field rather than going to the trouble of uploading a new annotated file. This works well for communicating the necessary revisions, but makes it inconvenient when I need to go back and re-review the corrected typeset files: if I want to view the text that I put in the Typesetting Task, to remind myself of which corrections I requested, I need to view the typesetting assignment in Admin.

It would be much more convenient if the text of the Typesetting Task was displayed on the Review Typesetting page

**Example**
Here is an article where I had a couple of corrections to request from the typesetter, one of which I definitely wouldn't remember the specific location of without referring back to this text. Screenshot from the Assign Typesetter page.
![image](https://github.com/user-attachments/assets/82a9ed84-bbda-4913-ad70-c1ece7dfe273)

Here is the Review Typestting page for that article. I would love to see the Typesetting Task text displayed above the Note from Typesetter text.
![image](https://github.com/user-attachments/assets/9f20159a-37a9-4e98-b7b7-2f9a5d2adb69)

Currently, if I want to view that text, I need to click "Edit in Admin" _before_ heading to the Review Typesetting screen, then scroll down to see the tagged version of the Typesetting Task.
![image](https://github.com/user-attachments/assets/4f377446-339a-45cc-9c56-db65b077ed90)

**Comment by joemull** [comment]
Thanks for reporting this @pgoussy! We are finally getting around to fixing the file management issues in typesetting, and I have included this in that work.
