### ISSUE TITLE
Typesetting 1.6 is not compatible with Janeway 1.6

### ISSUE THREAD

**Issue by yakky** [openlibhums/typesetting#220]
Contrary to the changelog (which states "Adds support for Django 4.2 and Janeway v1.6.0 by @mauromsl in https://github.com/openlibhums/typesetting/pull/210"), typesetting 1.6 includes commit https://github.com/openlibhums/typesetting/commit/1137d66ae1ae8a72858ba180df11e996039924e7 which bumps minimal janeway version to 1.7

IMHO the best solution would be to release 1.6.1 with the above commit reverted to ensure one could use typesetting plugin from a proper tag

**Comment by mauromsl** [comment]
Thanks @yakky, v1.6 of this plugin had some leaked features intended for a v1.7 release.

We've released a v1.6.1 on GitHub that should be compatible with Janeway v1.6.0+

https://github.com/openlibhums/typesetting/releases/tag/v1.6.1

**Comment by yakky** [comment]
@mauromsl thanks for the quick action!
